In [1]:
print("hello world")

hello world


In [2]:
import numpy as np

In [3]:
arr = np.array(12)

print(arr)

12


In [4]:
arr2 = np.array([12])

print(arr2)

[12]


In [5]:
arr3 = np.array([[12]])

print(arr3, arr3.ndim, arr.dtype )

[[12]] 2 int64


In [6]:
arr4 = np.array([[1,2,3],[3,4,8]])

print(arr4, arr4.ndim, arr4.shape)

[[1 2 3]
 [3 4 8]] 2 (2, 3)


In [7]:
import numpy as np

In [10]:
a = np.eye(5) 

print(a, a.dtype) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] float64


In [11]:
b = np.zeros((3,3))
print(b, b.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [15]:
d = np.empty((2,2))
d = d.astype("int32")
print(d, d.dtype)

[[1 0]
 [0 1]] int32


In [24]:
d = np.arange(0,10,2)
d = d.astype(str)

print(d, d.dtype)

['0' '2' '4' '6' '8'] <U21


In [29]:
e = np.linspace(0,10,30)
print(e, e.dtype)
e = e.astype("float32")
print(e, e.dtype)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ] float64
[ 0.         0.3448276  0.6896552  1.0344827  1.3793104  1.7241379
  2.0689654  2.413793   2.7586207  3.1034484  3.4482758  3.7931035
  4.137931   4.4827585  4.827586   5.172414   5.5172415  5.862069
  6.206897   6.551724   6.8965516  7.2413793  7.586207   7.9310346
  8.275862   8.620689   8.965517   9.310345   9.655172  10.       ] float32


In [39]:
f = np.array([1234567890, 2143567876, 1234567890], dtype=np.int32)
print(f, f.dtype)


[1234567890 2143567876 1234567890] int32


In [43]:
g = np.random.rand(3,3)
print(g, g.dtype)

[[0.07187493 0.06488627 0.92226955]
 [0.74819929 0.82112865 0.53714005]
 [0.39965363 0.72295541 0.88095374]] float64


In [58]:
h = np.random.randint(0,50, (3,3))
print(h, h.dtype)

[[11 42 18]
 [34 46 12]
 [48 15 17]] int32


In [59]:
i = np.random.random((3,3))
print(i, i.dtype)

[[0.83647322 0.42705607 0.93946092]
 [0.75961957 0.56483069 0.23772148]
 [0.24648957 0.57897695 0.33196119]] float64


In [70]:
a = np.array([1,2,3])
b = np.array([6,7,3])

sum = np.add(a,b)
print(sum)
sub = np.subtract(a,b)
print(sub)
mul = np.multiply(a,b)
print(mul)
div = np.divide(a,b)
print(div)

l = np.power(a,b)
print(l)

m = np.mod(a,b)
print(m)


[7 9 6]
[-5 -5  0]
[ 6 14  9]
[0.16666667 0.28571429 1.        ]
[  1 128  27]
[1 2 0]


In [72]:
abc = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.save("abc", abc)

abc2 = np.load("abc.npy")
print(abc2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
